INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'GOBERNADOR  DEL ESTADO YARACUY',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'ASISTENTES  GOBERNADOR.',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'SECRETARIO GENERAL DE GOBIERNO',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'SECRETARÍO DE SEGURIDAD CIUDADANA ',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'SECRETARIO DEL DESPACHO',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'SECRETARIA DE COMUNICACIÓN E INFORMACIÓN ',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'PRODUCCIÓN PROGRAMA RINDIENDO CUENTAS.',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'JEFE DE PROTOCOLO Y  RELACIONES PÚBLICAS ',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'SERVICIO INTEGRAL DE EMERGENCIA 171',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'SECRETARIA DE FINANZAS Y ADMINISTRACION.',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'DIRECTOR DE FINANZAS.',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'DIRECTOR DE ADMINISTRACIÓN',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'SECRETARIO DE INFRAESTRUCTURA',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'SECRETARIO DEL PODER COMUNAL Y PROTECCIÓN SOCIAL',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'DIRECCIÓN DE ATENCIÓN AL CIUDADANO.',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'JEFE DE LA ZONA EDUCATIVA',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'DIRECTOR DE EDUCACION.',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'SECRETARIA DE EDUCACION',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'SECRETARIO DE DESARROLLO ECONÓMICO',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'TESORERO GENERAL DEL ESTADO.',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'JEFE DE COMPRAS',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'CONSULTOR JURIDICO',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'JEFE DE ESTADÍSTICA E  INFORMÁTICA',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'SUPERVISOR DE MANTENIMIENTO DE LAS INSTALACIONES DEL PALACIO DE GOBIERNO',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'JEFE DE BIENES',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'OFICINA DE PRESUPUESTO',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'DIRECTORA (E)  DE LA OFICINA DE RECURSOS HUMANOS',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'SECRETARIA  PLANIFICACIÓN  Y DESARROLLO DE LA GOBERNACIÓN DEL ESTADO',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'UNIDAD DE AUDÍTORIA DE LA GOBERNACIÓN DEL ESTADO YARACUY ',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'OFICINA DE SEGUIMIENTO Y CONTROL.',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'DIRECCIÓN  DE ASUNTOS EDUCACIONALES Y CULTURALES',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'INSTITUTO  DE CULTURA DEL ESTADO YARACUY (I.C.E.Y.)',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'DIRECCIÓN DE  CULTURA DEL I.C.E.Y.',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'INSTITUTO AUTÓNOMO DE DEFENSA CIVIL Y DE APOYO EN CASOS DE EMERGENCIAS Y DESASTRES NATURALES DEL ESTADO YARACUY (IADC)',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'IMPRENTA DEL ESTADO YARACUY',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'FUNDACIÓN REGIONAL EL NIÑO SIMON',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'INSTITUTO AUTÓNOMO  PARA EL DEPORTE DEL EDO. YARACUY(FUNDEY)',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'INSTITUTO AUTONOMO DE LA SALUD DEL ESTADO YARACUY (PROSALUD)',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'FUNDACION PUEBLO SANO',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'INSTITUTO AUTÓNOMO  DE DESARROLLO ECONÓMICO DEL ESTADO YARACUY (I.A.D.E.Y)',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'SERVICIO AUTÓNOMO DE ADMINISTRACIÓN DE LA INFRAESTRUCTURA DEPORTIVA, CULTURAL Y TURÍSTICA DEL EDO. YARACUY. (S.A.I.E.Y)',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'INSTITUTO AUTÓNOMO  CONTRA LA POBREZA Y EXCLUSION SOCIAL  DEL ESTADO YARACUY.   (I.A.P.E.S.E.Y.)',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'INSTITUTO AUTÓNOMO DE INFRAESTRUCTURA',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'INSTITUTO DE HABITAT Y VIVIENDA DEL ESTADO YARACUY',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'INSTITUTO AUTÓNOMO DE VIALIDAD Y TRANSPORTE DEL ESTADO YARACUY (I.N.V.I.T.Y).',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'AGUAS DEL YARACUY',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'DIRECTOR DEL INSTITUTO AUTÓNOMO DE AYUDA A LOS FUNCIONARIOS DE SEGURIDAD CIUDADANA DEL GOBIERNO BOLIVARIANO DE YARACUY (I.A.A)',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'INAJUDEY. INSTITUTO NACIONAL DE LA JUVENTUD.DEL ESTADO YARACUY',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'JEFE DE LOS SERVICIOS MÉDICOS',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'CAJA DE AHORROS DE LA GOBERNACIÓN DEL ESTADO',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'CORPOTURISMO YARACUY.',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'SOCIEDAD  DE GARANTIAS  RECIPROCAS.',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'EMPRESA SOCIALISTA DE MINERALES NO METALICOS.',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'EMPRESA SOCIALISTA TRANSPORTE YARACUY.',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'FUNDACIÓN YARACUY BONITO.',2);
INSERT INTO tblmaestros(id_origen, stritema, id_sistema)    VALUES (13016,'BOMBEROS',2);
